### ISSUE TITLE
Increasing dmg numbers

### ISSUE THREAD

**Issue by Quantumdroid77** [Malekitsu/Maw-Mod-MMMerge#10]
![Screenshot (14)](https://github.com/Malekitsu/Maw-Mod-MMMerge/assets/171145248/ee3ad8c2-ce07-40e3-92e6-969441e8c56d)
![Screenshot (15)](https://github.com/Malekitsu/Maw-Mod-MMMerge/assets/171145248/b93392d9-cd9e-4220-b477-3876324ae410)
![Screenshot (13)](https://github.com/Malekitsu/Maw-Mod-MMMerge/assets/171145248/f01f6103-e7a6-441b-b8b7-08b963c147b3)
I got this bug. The damage display bar adding up all the attacks into a single number, and no idea what triggered it or how to undone it, and happened multiple times, only solution I know is new game....

**Comment by Malekitsu** [comment]
Hi! I guess you are using the packed version.
Download latest from here:
https://github.com/Malekitsu/Maw-Mod-MMMerge/archive/refs/heads/main.zip

**Comment by Quantumdroid77** [comment]
do I have to reinstall the game or its ok to simply overwrite?

**Comment by Malekitsu** [comment]
You can overwrite

**Comment by Quantumdroid77** [comment]
Thanks! I love this game, my childhood favourite! I made a balanced op party on doom (feels a slightly easier than the version i was playing before :O ). The new classes are dope, the bigger enemies are cool as well, and the multiplayer....oh the multiplayer, wish I have a friend who is interested in this game :/ by the way you can close this issue or remove it or whatever you like! you are the best, keep up!

**Comment by Malekitsu** [comment]
thanks, enjoy the game!
