### ISSUE TITLE
Item duplication!

### ISSUE THREAD

**Issue by Quantumdroid77** [Malekitsu/Maw-Mod-MMMerge#11]
I am not sure what was the exact cause of the bug, but already happened twice....each time I was in a dungeon, in combat, turn based mode on, opening my inventory and accidentally hit R or T and everything duplicated what that character was holding in their inventory!

![Screenshot (16)](https://github.com/Malekitsu/Maw-Mod-MMMerge/assets/171145248/825db51d-ccb0-4535-9164-3b01be7d65d1)
![Screenshot (17)](https://github.com/Malekitsu/Maw-Mod-MMMerge/assets/171145248/c3abe530-f0f8-40f5-91f9-a8d5bc751b98)
![Screenshot (18)](https://github.com/Malekitsu/Maw-Mod-MMMerge/assets/171145248/6362040d-2675-4442-a349-a24038aeb22d)
![Screenshot (19)](https://github.com/Malekitsu/Maw-Mod-MMMerge/assets/171145248/410f1ddb-aa30-4145-bc19-e10a82729acf)
![Screenshot (20)](https://github.com/Malekitsu/Maw-Mod-MMMerge/assets/171145248/efdf3665-5d4a-418b-b239-4f636dcf06b6)

**Comment by Malekitsu** [comment]
thanks, will investigate

**Comment by Malekitsu** [comment]
thanks, the bug have been found and fixed ;)
