### ISSUE TITLE
Crash on newest scripts

### ISSUE THREAD

**Issue by DrunkenDonkey80** [Malekitsu/Maw-Mod-MMMerge#6]
The newest versions are giving errors upon launch and new game crashes, clean install + mmmerge zip + archive overwrite:

`C:\games\MIGHTA~2\Scripts\General\MenuExtraSettings.lua:248: attempt to call field 'GetRegistryValue' (a nil value)

stack traceback:
	C:\games\MIGHTA~2\Scripts\General\MenuExtraSettings.lua: in function 'v'
	C:\games\MIGHTA~2\Scripts/Core/EventsList.lua:101: in function <C:\games\MIGHTA~2\Scripts/Core/EventsList.lua:96>

local variables of 'v':
	(*temporary) = 107
	(*temporary) = (table: 0x0515a788)
	(*temporary) = 13
	(*temporary) = 27
	(*temporary) = (table: 0x05375190)
	(*temporary) = (table: 0x05375c50)
	(*temporary) = (table: 0x066781a0)
	(*temporary) = (table: 0x044c2b20)
	(*temporary) = nil
	(*temporary) = "m_framelimit"
	(*temporary) = 0
	(*temporary) = "BolsterAmount"
	(*temporary) = (function: 0x07760540)
	(*temporary) = (function: 0x06819800)
	(*temporary) = 100
	(*temporary) = 50
	(*temporary) = 250
	(*temporary) = 50
	(*temporary) = "attempt to call field 'GetRegistryValue' (a nil value)"

upvalues of 'v':
	NewSettingsPage = (function: 0x066ee6c8)
	CurrentPage = 1
	Pages = (table: 0x066ee6a0)
	ExitExtSetScreen = (function: 0x06713f68)
	OnOffTumbler = (function: 0x066ee730)
	NumberRegulator = (function: 0x066ee848)
	MF = (table: 0x052dff40)

C:\games\MIGHTA~2\Scripts\General\zzClasses.lua:48: array index (56) out of bounds [0, 55]

stack traceback:
	[C]: in function 'error'
	C:\games\MIGHTA~2\Scripts/Core/RSMem.lua:1429: in function '__index'
	C:\games\MIGHTA~2\Scripts\General\zzClasses.lua:48: in function 'v'
	C:\games\MIGHTA~2\Scripts/Core/EventsList.lua:101: in function <C:\games\MIGHTA~2\Scripts/Core/EventsList.lua:96>

arguments of '__index':
	t = (table: 0x054a2fa8)
	a = 56
	v = nil

local variables of '__index':
	aorig = 56
	a1 = 56
	n = 56

upvalues of '__index':
	ptr = nil
	u4 = (table: 0x0454b2f8)
	GetPtr = (function: 0x04543db8)
	obj = (table: 0x0673a048)
	o = 124395164
	assertnum = (function: 0x045438b0)
	error = (function: 0x05912d10)
	type = (function: builtin#3)
	SetLen = nil
	low = 0
	GetLen = (function: 0x04579410)
	lenP = nil
	lenA = nil
	size = 1
	count = 56
	_index = nil
	_newindex = nil
	tonumber = (function: builtin#17)
	beyondLen = nil
	f = (function: 0x05971c80)
	format = (function: builtin#91)
	sOutOfBounds = "array index (%s) out of bounds [%s, %s]"
	tostring = (function: builtin#18)
	tostring2 = (function: 0x04544a58)

> `

**Comment by Malekitsu** [comment]
Solved with fresh install?

**Comment by DrunkenDonkey80** [comment]
Clean install with everything newly downloaded and it now works!! Thanks

**Comment by Malekitsu** [comment]
nice, closing then ;)
